openapi: 3.0.3
info:
  title: ApiShip Auth
  contact:
    name: Техническая поддержка
    email: support@apiship.ru
    url: 'https://support.apiship.ru/'
  termsOfService: 'https://apiship.ru/offer.pdf'
  description: |
    **Документация сервиса авторизации ApiShip**

    **Подробнее об ApiShip на [apiship.ru](https://apiship.ru) или задайте вопрос на [info@apiship.ru](mailto:info@apiship.ru)**
  version: 1.0.0
servers:
  - url: /v1
security:
  - token: [ ]
paths:
  /billing/apidq/check:
    post:
      security:
        - { }
      tags:
        - apidqBilling
      summary: Проверка биллинга операции для APIDQ
      operationId: ApidqBillingCheck
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CheckBillingRequest'
        required: true
      responses:
        200:
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BillingResponse'
        4XX:
          $ref: '#/components/responses/ServiceErrorResponse'
        5XX:
          $ref: '#/components/responses/ServerErrorResponse'
  /auth/tokens/validation:
    post:
      security:
        - { }
      tags:
        - auth
      summary: Проверить токен
      operationId: ValidationToken
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ValidateTokenRequest'
        required: true
      responses:
        200:
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenResponse'
        4XX:
          $ref: '#/components/responses/ServiceErrorResponse'
        5XX:
          $ref: '#/components/responses/ServerErrorResponse'
  /auth/tokens:
    get:
      tags:
        - auth
      summary: Получить список токенов
      operationId: GetListToken
      parameters:
        - name: permissions
          in: query
          description: 'Фильтр по правам. Токен замаскирован.'
          schema:
            maximum: 5000
            minimum: 0
            type: array
            items:
              type: string
      responses:
        200:
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListTokenResponse'
        4XX:
          $ref: '#/components/responses/ServiceErrorResponse'
        5XX:
          $ref: '#/components/responses/ServerErrorResponse'
    post:
      tags:
        - auth
      summary: Создать токен
      operationId: CreateToken
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTokenRequest'
        required: true
      responses:
        200:
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenResponse'
        4XX:
          $ref: '#/components/responses/ServiceErrorResponse'
        5XX:
          $ref: '#/components/responses/ServerErrorResponse'
components:
  securitySchemes:
    token:
      type: apiKey
      name: Authorization
      in: header
      description: 'Токен необходимо взять в методе [авторизации](#/users/login). Если аккаунта в системе нет, то зарегистрироваться через [API](#/users/signup) или через [личный кабинет](https://a.apiship.ru/#/signup).'
  schemas:
    CheckBillingRequest:
      type: object
      properties:
        method:
          type: string
          description: "Метода запроса apidq.clean или apidq.suggest"
        token:
          type: string
          description: "Токен с правами для выполнения операции"
    BillingResponse:
      type: object
      properties:
        success:
          type: boolean
          description: "Операция для токена разрешена"
    ValidateTokenRequest:
      type: object
      properties:
        permissions:
          type: array
          description: "Массив прав токена"
          items:
            type: string
        token:
          type: string
          description: "Токена"
    GetTokensRequest:
      type: object
      properties:
        permissions:
          type: array
          description: "Массив прав токена"
          items:
            type: string
    CreateTokenRequest:
      type: object
      properties:
        permissions:
          type: array
          description: "Массив прав токена"
          items:
            type: string
        expire:
          type: string
          format: date-time
          description: "Время действия токена"
    TokenResponse:
      type: object
      properties:
        userId:
          type: string
          description: "ID пользователя ApiShip"
        token:
          type: string
          maxLength: 32
          readOnly: true
        expire:
          type: string
          format: date-time
          description: "Время действия токена"
        permissions:
          type: array
          description: "Массив прав токена"
          items:
            type: string
    PaginationMeta:
      type: object
      properties:
        total:
          type: integer
        offset:
          type: integer
        limit:
          type: integer
    ListTokenResponse:
      type: object
      properties:
        rows:
          type: array
          description: Массив объектов токенов
          items:
            $ref: '#/components/schemas/TokenResponse'
        meta:
          $ref: '#/components/schemas/PaginationMeta'
    ServerError:
      type: object
      properties:
        code:
          type: integer
          description: Код ошибки сервера
        message:
          type: string
          description: Описание ошибки сервера
    ServiceError:
      type: object
      properties:
        code:
          type: string
          description: |
            Код ошибки:
            * '040301' - (HTTP-STATUS: 403) Доступ запрещен;
            * '040302' - (HTTP-STATUS: 403) Некорректный пароль;
            * '040303' - (HTTP-STATUS: 403) Пользователь с указанным логином не существует;
            * '040101' - (HTTP-STATUS: 401) Некорректный ключ безопасности;
            * '040304' - (HTTP-STATUS: 403) Срок службы ключа безопасности истек;
            * '040305' - (HTTP-STATUS: 403) Заказ принадлежит другому клиенту;
            * '040306' - (HTTP-STATUS: 403) Служба доставки не поддерживает отмену заказа;
            * '040307' - (HTTP-STATUS: 400) Служба доставки не поддерживает отмену заявки;
            * '040308' - (HTTP-STATUS: 403) Недостаточно прав для вызова данного метода;
            * '040309' - (HTTP-STATUS: 403) Чек принадлежит другому клиенту;
            * '040080' - (HTTP-STATUS: 404) Указанного заказа не существует;
            * '040081' - (HTTP-STATUS: 400) Указанный заказ уже отменен;
            * '040082' - (HTTP-STATUS: 400) Указанная заявка уже отменена;
            * '040083' - (HTTP-STATUS: 400) Указанная заявка не была передана в СД;
            * '040084' - (HTTP-STATUS: 400) Заявка не может быть отменена, подробнее в errors;
            * '040085' - (HTTP-STATUS: 400) Чек не был передан в ОФД;
            * '040086' - (HTTP-STATUS: 400) Ошибка при получении статуса чека;
            * '040087' - (HTTP-STATUS: 404) Указанного чека не существует;
            * '040088' - (HTTP-STATUS: 400) Ошибка при создании заказа в СД;
            * '040089' - (HTTP-STATUS: 400) Ошибка при обновлении заказа в СД;
            * '040000' - (HTTP-STATUS: 400) Общая ошибка валидации, смотрите документацию;
            * '040001' - (HTTP-STATUS: 400) Ошибка валидации при попытке аутентификации;
            * '040002' - (HTTP-STATUS: 400) Ошибка валидации;
            * '040003' - (HTTP-STATUS: 400) Ошибка валидации при попытке рассчитать стоимость доставки;
            * '040004' - (HTTP-STATUS: 400) Неправильная кодировка. Кодировка должна быть UTF-8;
            * '040005' - (HTTP-STATUS: 400) Для Вашей компании нет параметров доступа в данную службы доставки;
            * '040006' - (HTTP-STATUS: 400) У Вашей компании нет подключенных СД;
            * '040010' - (HTTP-STATUS: 400) Фильтр не валидный, смотрите документацию;
            * '040011' - (HTTP-STATUS: 400) В фильтре присутствуют поля, по которым фильтрация не осуществляется;
            * '040012' - (HTTP-STATUS: 400) В поле fields присутствуют поля, которые не доступны для клиентов;
            * '040013' - (HTTP-STATUS: 400) В поле with присутствуют поля, которые не доступны для клиентов или недопустимы;
            * '040014' - (HTTP-STATUS: 400) Не удалось получить файл для импорта;
            * '040015' - (HTTP-STATUS: 400) Ошибка создания кода адреса в СД;
            * '040016' - (HTTP-STATUS: 404) Не найдено;
            * '040017' - (HTTP-STATUS: 400) Неверная ссылка;
            * '040901' - (HTTP-STATUS: 409) Пользователь с таким логином уже существует;
            * '040902' - (HTTP-STATUS: 409) Параметры подключения для данной СД уже созданы;
            * '050001' - (HTTP-STATUS: 500) Свяжитесь с администрацией;
            * '060001' - (HTTP-STATUS: 402) Пополните баланс для использования сервиса калькуляции;
          example: '040002'
          enum:
            - '040301'
            - '040302'
            - '040303'
            - '040101'
            - '040304'
            - '040305'
            - '040306'
            - '040307'
            - '040308'
            - '040309'
            - '040080'
            - '040081'
            - '040082'
            - '040083'
            - '040084'
            - '040085'
            - '040086'
            - '040087'
            - '040088'
            - '040089'
            - '040000'
            - '040001'
            - '040002'
            - '040003'
            - '040004'
            - '040005'
            - '040006'
            - '040010'
            - '040011'
            - '040012'
            - '040013'
            - '040014'
            - '040015'
            - '040016'
            - '040017'
            - '040901'
            - '040902'
            - '050001'
            - '060001'
        message:
          type: string
          description: Сообщение об ошибке. Сервер отдает это поле всегда. Остальные могут не отдаваться в различных сценариях.
          example: Ошибка валидации
        description:
          type: string
          description: Описание ошибки
          example: Описание ошибки валидации
        moreInfo:
          type: string
          description: Дополнительная информация для решения ошибки
          example: Вопросы пишите на адрес support@apiship.ru
        errors:
          type: array
          description: Детализированная информация об ошибке
          items:
            type: object
            properties:
              field:
                type: string
                description: Названия поля
              message:
                type: string
                description: Детальное сообщение об ошибке
      description: Bad request
  responses:
    ServiceErrorResponse:
      description: Bad request
      headers:
        X-Tracing-Id:
          $ref: '#/components/headers/traceId'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ServiceError'
        application/xml:
          schema:
            $ref: '#/components/schemas/ServiceError'
    ServerErrorResponse:
      description: Server error
      headers:
        X-Tracing-Id:
          $ref: '#/components/headers/traceId'
      content:
        application/json:
          schema:
            oneOf:
              - $ref: '#/components/schemas/ServerError'
              - $ref: '#/components/schemas/ServiceError'
        application/xml:
          schema:
            oneOf:
              - $ref: '#/components/schemas/ServerError'
              - $ref: '#/components/schemas/ServiceError'
  headers:
    traceId:
      description: 'ИД запроса, по которому служба поддержки может найти логи'
      schema:
        type: string
        maximum: 32
        readOnly: true
        externalDocs:
          url: 'https://support.apiship.ru/knowledge_base/item/189024?sid=43514'